Attribute VB_Name = "Globals"
'' Global Variables
Global info As String
Global Canada As Integer
Global debugmode As Integer
Global Color As String
Global idleMessage As String
Global idletimeset As Integer
Global fudd As Integer
Global uptimesec As Integer
Global uptimemin As Integer
Global uptimehour As Integer
Global uptimedays As Integer
Global uptimeweek As Integer
Global uptimemonth As Integer
Global moo As Integer
Global leetspeak As Integer
Global LastW As String
Global LastCW As String
Global LastM As String
Global LastSW As String
Global LastSM As String
Global BanCount As Integer
Global KickCount As Integer
Global JoinCount As Integer
Global beforetext As String
Global postpend As String
Global targetuser As String
Global targetusername As String
